# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wheel Of Fortune

on:
  # Triggers daily
  schedule:
    - cron: '0 22 * * *' #runs at 22:00 UTC everyday (5pm ET)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    #     runs-on: ubuntu-latest # figure out how to run on ubuntu later
    runs-on: macos-10.15
    strategy:
    matrix:
      username: ['LOGIN_USERNAME1', 'LOGIN_USERNAME2']
      password: ['LOGIN_PASSWORD1', 'LOGIN_PASSWORD2']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          brew install yarn
          yarn install

      - name: run wheel spin
        env:
          LOGIN_USERNAME: ${{ secrets[matrix.username] }}
          LOGIN_PASSWORD: ${{ secrets[matrix.password] }}
        run: |
          yarn start
