# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wheel Of Fortune

on:
  # Triggers daily
  schedule:
    - cron: '0 17 * * *' #runs at 17:00 UTC everyday (12pm ET)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    #     runs-on: ubuntu-latest # figure out how to run on ubuntu later
    runs-on: macos-10.15
    # multi-account support
    # reference: https://stackoverflow.com/a/59310425/3763996
    strategy:
      matrix:
        username:
          [
            'LOGIN_USERNAME1',
            'LOGIN_USERNAME2',
            'LOGIN_USERNAME3',
            'LOGIN_USERNAME4',
            'LOGIN_USERNAME5',
            'LOGIN_USERNAME6',
            'LOGIN_USERNAME7',
          ]
        password: ['LOGIN_PASSWORD'] # use same password for now, this is because matrix will create jobs for ALL combinations if there are multiple values for password

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: |
          brew install yarn
          yarn install

      - name: run wheel spin
        env:
          LOGIN_USERNAME: ${{ secrets[matrix.username] }}
          LOGIN_PASSWORD: ${{ secrets[matrix.password] }}
        run: |
          yarn start
